# action.yml
name: 'Zulip Archive'
description: 'Publish Zulip archive in GitHub pages'
inputs:
  zulip_organization_url:
    description: 'URL of Zulip organization'
    required: true
  zulip_bot_email:
    description: 'Email of the Zulip bot'
    required: true
  zulip_bot_key:
    description: 'API key of the Zulip bot'
    required: true
  github_personal_access_token:
    description: 'GitHub personal access token'
    required: false
    default: 'none'
  github_actions_token:
    description: 'GitHub Actions Token'
    required: false
    default: 'none'
  delete_history:
    description: 'If enabled, will delete the archive history while keeping the most recent version'
    required: false
    default: false
  archive_branch:
    description: 'Branch where to commit archive files (should coincide with GH Pages branch)'
    # legacy
    required: false
    default: 'gh-pages'
  site_url:
    description: 'URL where site will be hosted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.zulip_organization_url }}
    - ${{ inputs.zulip_bot_email }}
    - ${{ inputs.zulip_bot_key }}
    - ${{ inputs.github_personal_access_token }}
    - ${{ inputs.github_actions_token }}
    - ${{ inputs.delete_history }}
    - ${{ inputs.archive_branch }}
    - ${{ inputs.site_url }}
